apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  JWT_SECRET: bmpnK0xtaVF3Vm02aEJmaFkyZ2ROcmpUZERpN2kxT2w3cm1DZWZoaDR3VT0NCg== # JWT_SECRET codificado em Base64
  # DATABASE_PASSWORD: <BASE64_ENCODED_DB_PASSWORD> # Se você quiser gerenciar a senha do DB via Secret
